// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.study.netty.protobuf;

public final class Student {
  private Student() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentDefineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.study.netty.protobuf.StudentDefine)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>double hight = 3;</code>
     */
    double getHight();

    /**
     * <code>double weight = 4;</code>
     */
    double getWeight();

    /**
     * <code>repeated string postition = 5;</code>
     */
    java.util.List<java.lang.String>
        getPostitionList();
    /**
     * <code>repeated string postition = 5;</code>
     */
    int getPostitionCount();
    /**
     * <code>repeated string postition = 5;</code>
     */
    java.lang.String getPostition(int index);
    /**
     * <code>repeated string postition = 5;</code>
     */
    com.google.protobuf.ByteString
        getPostitionBytes(int index);
  }
  /**
   * Protobuf type {@code com.study.netty.protobuf.StudentDefine}
   */
  public  static final class StudentDefine extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.study.netty.protobuf.StudentDefine)
      StudentDefineOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StudentDefine.newBuilder() to construct.
    private StudentDefine(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StudentDefine() {
      name_ = "";
      age_ = 0;
      hight_ = 0D;
      weight_ = 0D;
      postition_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StudentDefine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 25: {

              hight_ = input.readDouble();
              break;
            }
            case 33: {

              weight_ = input.readDouble();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                postition_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              postition_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          postition_ = postition_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.study.netty.protobuf.Student.internal_static_com_study_netty_protobuf_StudentDefine_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.study.netty.protobuf.Student.internal_static_com_study_netty_protobuf_StudentDefine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.study.netty.protobuf.Student.StudentDefine.class, com.study.netty.protobuf.Student.StudentDefine.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int HIGHT_FIELD_NUMBER = 3;
    private double hight_;
    /**
     * <code>double hight = 3;</code>
     */
    public double getHight() {
      return hight_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 4;
    private double weight_;
    /**
     * <code>double weight = 4;</code>
     */
    public double getWeight() {
      return weight_;
    }

    public static final int POSTITION_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList postition_;
    /**
     * <code>repeated string postition = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPostitionList() {
      return postition_;
    }
    /**
     * <code>repeated string postition = 5;</code>
     */
    public int getPostitionCount() {
      return postition_.size();
    }
    /**
     * <code>repeated string postition = 5;</code>
     */
    public java.lang.String getPostition(int index) {
      return postition_.get(index);
    }
    /**
     * <code>repeated string postition = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPostitionBytes(int index) {
      return postition_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (hight_ != 0D) {
        output.writeDouble(3, hight_);
      }
      if (weight_ != 0D) {
        output.writeDouble(4, weight_);
      }
      for (int i = 0; i < postition_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, postition_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (hight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, hight_);
      }
      if (weight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, weight_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < postition_.size(); i++) {
          dataSize += computeStringSizeNoTag(postition_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPostitionList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.study.netty.protobuf.Student.StudentDefine)) {
        return super.equals(obj);
      }
      com.study.netty.protobuf.Student.StudentDefine other = (com.study.netty.protobuf.Student.StudentDefine) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (
          java.lang.Double.doubleToLongBits(getHight())
          == java.lang.Double.doubleToLongBits(
              other.getHight()));
      result = result && (
          java.lang.Double.doubleToLongBits(getWeight())
          == java.lang.Double.doubleToLongBits(
              other.getWeight()));
      result = result && getPostitionList()
          .equals(other.getPostitionList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + HIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHight()));
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWeight()));
      if (getPostitionCount() > 0) {
        hash = (37 * hash) + POSTITION_FIELD_NUMBER;
        hash = (53 * hash) + getPostitionList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.netty.protobuf.Student.StudentDefine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.study.netty.protobuf.Student.StudentDefine prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.study.netty.protobuf.StudentDefine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.study.netty.protobuf.StudentDefine)
        com.study.netty.protobuf.Student.StudentDefineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.study.netty.protobuf.Student.internal_static_com_study_netty_protobuf_StudentDefine_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.study.netty.protobuf.Student.internal_static_com_study_netty_protobuf_StudentDefine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.study.netty.protobuf.Student.StudentDefine.class, com.study.netty.protobuf.Student.StudentDefine.Builder.class);
      }

      // Construct using com.study.netty.protobuf.Student.StudentDefine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        hight_ = 0D;

        weight_ = 0D;

        postition_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.study.netty.protobuf.Student.internal_static_com_study_netty_protobuf_StudentDefine_descriptor;
      }

      public com.study.netty.protobuf.Student.StudentDefine getDefaultInstanceForType() {
        return com.study.netty.protobuf.Student.StudentDefine.getDefaultInstance();
      }

      public com.study.netty.protobuf.Student.StudentDefine build() {
        com.study.netty.protobuf.Student.StudentDefine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.study.netty.protobuf.Student.StudentDefine buildPartial() {
        com.study.netty.protobuf.Student.StudentDefine result = new com.study.netty.protobuf.Student.StudentDefine(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.age_ = age_;
        result.hight_ = hight_;
        result.weight_ = weight_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          postition_ = postition_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.postition_ = postition_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.study.netty.protobuf.Student.StudentDefine) {
          return mergeFrom((com.study.netty.protobuf.Student.StudentDefine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.study.netty.protobuf.Student.StudentDefine other) {
        if (other == com.study.netty.protobuf.Student.StudentDefine.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getHight() != 0D) {
          setHight(other.getHight());
        }
        if (other.getWeight() != 0D) {
          setWeight(other.getWeight());
        }
        if (!other.postition_.isEmpty()) {
          if (postition_.isEmpty()) {
            postition_ = other.postition_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePostitionIsMutable();
            postition_.addAll(other.postition_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.study.netty.protobuf.Student.StudentDefine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.study.netty.protobuf.Student.StudentDefine) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private double hight_ ;
      /**
       * <code>double hight = 3;</code>
       */
      public double getHight() {
        return hight_;
      }
      /**
       * <code>double hight = 3;</code>
       */
      public Builder setHight(double value) {
        
        hight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double hight = 3;</code>
       */
      public Builder clearHight() {
        
        hight_ = 0D;
        onChanged();
        return this;
      }

      private double weight_ ;
      /**
       * <code>double weight = 4;</code>
       */
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>double weight = 4;</code>
       */
      public Builder setWeight(double value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight = 4;</code>
       */
      public Builder clearWeight() {
        
        weight_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList postition_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePostitionIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          postition_ = new com.google.protobuf.LazyStringArrayList(postition_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string postition = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPostitionList() {
        return postition_.getUnmodifiableView();
      }
      /**
       * <code>repeated string postition = 5;</code>
       */
      public int getPostitionCount() {
        return postition_.size();
      }
      /**
       * <code>repeated string postition = 5;</code>
       */
      public java.lang.String getPostition(int index) {
        return postition_.get(index);
      }
      /**
       * <code>repeated string postition = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPostitionBytes(int index) {
        return postition_.getByteString(index);
      }
      /**
       * <code>repeated string postition = 5;</code>
       */
      public Builder setPostition(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePostitionIsMutable();
        postition_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string postition = 5;</code>
       */
      public Builder addPostition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePostitionIsMutable();
        postition_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string postition = 5;</code>
       */
      public Builder addAllPostition(
          java.lang.Iterable<java.lang.String> values) {
        ensurePostitionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, postition_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string postition = 5;</code>
       */
      public Builder clearPostition() {
        postition_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string postition = 5;</code>
       */
      public Builder addPostitionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePostitionIsMutable();
        postition_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.study.netty.protobuf.StudentDefine)
    }

    // @@protoc_insertion_point(class_scope:com.study.netty.protobuf.StudentDefine)
    private static final com.study.netty.protobuf.Student.StudentDefine DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.study.netty.protobuf.Student.StudentDefine();
    }

    public static com.study.netty.protobuf.Student.StudentDefine getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StudentDefine>
        PARSER = new com.google.protobuf.AbstractParser<StudentDefine>() {
      public StudentDefine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StudentDefine(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StudentDefine> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StudentDefine> getParserForType() {
      return PARSER;
    }

    public com.study.netty.protobuf.Student.StudentDefine getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_study_netty_protobuf_StudentDefine_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_study_netty_protobuf_StudentDefine_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\030com.study.netty.protobu" +
      "f\"\\\n\rStudentDefine\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030" +
      "\002 \001(\005\022\r\n\005hight\030\003 \001(\001\022\016\n\006weight\030\004 \001(\001\022\021\n\t" +
      "postition\030\005 \003(\tB\tB\007Studentb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_study_netty_protobuf_StudentDefine_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_study_netty_protobuf_StudentDefine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_study_netty_protobuf_StudentDefine_descriptor,
        new java.lang.String[] { "Name", "Age", "Hight", "Weight", "Postition", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
